---
title: 'Modelling cancer (all, solid and hematological) by years since the cancer diagnosis'
output:
  html_document:
    code_folding: hide
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 4
    toc_float: yes
highlight: tango
theme: united
toc: yes
toc_depth: 4
toc_float: yes
editor_options:
  chunk_output_type: console
---
  
```{r options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, comment = FALSE)
options(scipen = 999)
```

```{r packages, include=FALSE}
# packages -----
# install.packages("seplyr")
library(kableExtra)
library(dplyr)
library(ggplot2)
library(rms)
library(stargazer)
library(knitr)
library(stringr)
library(tidyr)
library(seplyr)
```


```{r data, include=FALSE}
load("M:/Elena - R/Multi-state  cancer/1 data prep/working.data.Rda")

dd <<- datadist(r); options(datadist = "dd")

nice.num <- function(x) {
  prettyNum(x, big.mark = ",", nsmall = 0, digits = 0, scientific = FALSE)
}
nice.num2 <- function(x) {
  prettyNum(x, big.mark = ",", nsmall = 2, digits = 2, scientific = FALSE)
}

windowsFonts(A = windowsFont("Times New Roman"))  # Specify font
```

```{r}
# Define which cancers to analyze
cancers <- c("hematological",
             "solid")
```


```{r}
# function for models - only fully adjusted models
get.models <- function(cancers,   #select cancer type of interest
                       transition.data,  # data for transition of interest
                       transition.name) {

  # models<-list()
  summary.models <- NULL

  ## All cancers
  ## Overall
  if (transition.name %in%
    c("From general population to diagnosed with COVID-19",
      "From diagnosed with COVID-19 to hospitalised with COVID-19",
      "From general population to death")) {
    m.working <- cph(Surv(time, status) ~  cancer +
      rcs(age, 5) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data,
    iter.max = 200)

  } else if (transition.name %in%
    c("From general population to hospitalised with COVID-19",
      "From diagnosed with COVID-19 to death")) {
    m.working <- cph(Surv(time, status) ~  cancer  +
      pol(age, 2) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data,
    iter.max = 200)
    
  } else {
    m.working <- cph(Surv(time, status) ~  cancer +
      rcs(age, 3) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data,
    iter.max = 200)
  }
  working.summary <- as.data.frame(summary(m.working, antilog = FALSE))
  working.summary$var <- row.names(working.summary)
  working.summary$gender <- "Overall"
  working.summary$c_status <- "Overall"
  working.summary$model <- "Fully adjusted"
  working.summary$transition.name <- transition.name
  working.summary <- working.summary %>%
    mutate(hr = exp(Effect),
      hr.low = exp(`Lower 0.95`),
      hr.high = exp(`Upper 0.95`)) %>%
    select(transition.name, var, model, gender,
      c_status, hr, hr.low, hr.high)
  # output
  summary.models <- rbind(summary.models,
    working.summary)

  ##  cancers diagnosed <1year

  if (transition.name %in%
    c("From general population to diagnosed with COVID-19",
      "From diagnosed with COVID-19 to hospitalised with COVID-19",
      "From general population to death")) {
    m.working <- cph(Surv(time, status) ~  cancer +
      rcs(age, 5) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data %>%
      filter(cancer == 0 | c_status == "< 1 year"),
    iter.max = 200)

  } else if (transition.name %in%
    c("From general population to hospitalised with COVID-19",
      "From diagnosed with COVID-19 to death")) {
    m.working <- cph(Surv(time, status) ~  cancer +
      pol(age, 2) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data %>%
      filter(cancer == 0 | c_status == "< 1 year"),
    iter.max = 200)

  } else {
    m.working <- cph(Surv(time, status) ~  cancer +
      rcs(age, 3) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data %>%
      filter(cancer == 0 | c_status == "< 1 year"),
    iter.max = 200)

  }
  working.summary <- as.data.frame(summary(m.working, antilog = FALSE))
  working.summary$var <- row.names(working.summary)
  working.summary$gender <- "Overall"
  working.summary$c_status <- "< 1 year"
  working.summary$model <- "Fully adjusted"
  working.summary$transition.name <- transition.name
  working.summary <- working.summary %>%
    mutate(hr = exp(Effect),
      hr.low = exp(`Lower 0.95`),
      hr.high = exp(`Upper 0.95`)) %>%
    select(transition.name, var, model, gender,
      c_status, hr, hr.low, hr.high)
  # output
  summary.models <- rbind(summary.models,
    working.summary)

  ##  cancers diagnosed 1-5 year
  if (transition.name %in%
    c("From general population to diagnosed with COVID-19",
      "From diagnosed with COVID-19 to hospitalised with COVID-19",
      "From general population to death")) {
    m.working <- cph(Surv(time, status) ~  cancer +
      rcs(age, 5) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data %>%
      filter(cancer == 0 | c_status == "1-5 years"),
    iter.max = 200)

  } else if (transition.name %in%
    c("From general population to hospitalised with COVID-19",
      "From diagnosed with COVID-19 to death")) {
    m.working <- cph(Surv(time, status) ~  cancer +
      pol(age, 2) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data %>%
      filter(cancer == 0 | c_status == "1-5 years"),
    iter.max = 200)

  } else {
    m.working <- cph(Surv(time, status) ~  cancer +
      rcs(age, 3) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data %>%
      filter(cancer == 0 | c_status == "1-5 years"),
    iter.max = 200)
  }
  working.summary <- as.data.frame(summary(m.working, antilog = FALSE))
  working.summary$var <- row.names(working.summary)
  working.summary$gender <- "Overall"
  working.summary$c_status <- "1-5 years"
  working.summary$model <- "Fully adjusted"
  working.summary$transition.name <- transition.name
  working.summary <- working.summary %>%
    mutate(hr = exp(Effect),
      hr.low = exp(`Lower 0.95`),
      hr.high = exp(`Upper 0.95`)) %>%
    select(transition.name, var, model, gender,
      c_status, hr, hr.low, hr.high)
  # output
  summary.models <- rbind(summary.models,
    working.summary)

  ## cancers diagnosed >5y ago
  if (transition.name %in%
    c("From general population to diagnosed with COVID-19",
      "From diagnosed with COVID-19 to hospitalised with COVID-19",
      "From general population to death")) {
    m.working <- cph(Surv(time, status) ~ cancer +
      rcs(age, 5) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data   %>%
      filter(cancer == 0 | c_status == ">5years"),
    iter.max = 200)

  } else if (transition.name %in%
    c("From general population to hospitalised with COVID-19",
      "From diagnosed with COVID-19 to death")) {
    m.working <- cph(Surv(time, status) ~  cancer +
      pol(age, 2) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data   %>%
      filter(cancer == 0 | c_status == ">5years"),
    iter.max = 200)
  } else {
    m.working <- cph(Surv(time, status) ~  cancer +
      rcs(age, 3) + gender +
      medea + smoke.all_time +
      a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
      a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity,
    surv = TRUE, x = TRUE, y = TRUE,
    data = transition.data   %>%
      filter(cancer == 0 | c_status == ">5years"),
    iter.max = 200)
  }
  working.summary <- as.data.frame(summary(m.working, antilog = FALSE))
  working.summary$var <- row.names(working.summary)
  working.summary$gender <- "Overall"
  working.summary$c_status <- ">5years"
  working.summary$model <- "Fully adjusted"
  working.summary$transition.name <- transition.name
  working.summary <- working.summary %>%
    mutate(hr = exp(Effect),
      hr.low = exp(`Lower 0.95`),
      hr.high = exp(`Upper 0.95`)) %>%
    select(transition.name, var, model, gender,
      c_status, hr, hr.low, hr.high)
  # output
  summary.models <- rbind(summary.models,
    working.summary)

  summary.models

  ## selected cancers

  for (i in 1:length(cancers)) {
    message(paste0("working on cancer ", i, "( ", cancers[i], ")"))
    working.cancer <- cancers[i]

    #  Overall models
    if (transition.name %in%
      c("From general population to diagnosed with COVID-19",
        "From diagnosed with COVID-19 to hospitalised with COVID-19",
        "From general population to death")) {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+rcs(age,5)+
                medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 | ", cancers[i], "==1")),
      iter.max = 200)


    } else if (transition.name %in%
      c("From general population to hospitalised with COVID-19",
        "From diagnosed with COVID-19 to death")) {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+pol(age,2)+
                medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 | ", cancers[i], "==1")),
      iter.max = 200)
    } else {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+rcs(age,3)+
                medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 | ", cancers[i], "==1")),
      iter.max = 200)
    }
    working.summary <- as.data.frame(summary(m.working, antilog = FALSE))
    working.summary$var <- row.names(working.summary)
    working.summary$gender <- "Overall"
    working.summary$c_status <- "Overall"
    working.summary$model <- "Fully adjusted"
    working.summary$transition.name <- transition.name
    working.summary <- working.summary %>%
      mutate(hr = exp(Effect),
        hr.low = exp(`Lower 0.95`),
        hr.high = exp(`Upper 0.95`)) %>%
      select(transition.name, var, model, gender,
        c_status, hr, hr.low, hr.high)
    # output
    summary.models <- rbind(summary.models,
      working.summary)

    ## <1 year cancers

    if (transition.name %in%
      c("From general population to diagnosed with COVID-19",
        "From diagnosed with COVID-19 to hospitalised with COVID-19",
        "From general population to death")) {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+rcs(age,5)+
                medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\"< 1 year\")")),
      iter.max = 200)

    } else if (transition.name %in%
      c("From general population to hospitalised with COVID-19",
        "From diagnosed with COVID-19 to death")) {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+pol(age,2)+
                medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\"< 1 year\")")),
      iter.max = 200)
    } else {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+rcs(age,3)+
                medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\"< 1 year\")")),
      iter.max = 200)
    }
    working.summary <- as.data.frame(summary(m.working, antilog = FALSE))
    working.summary$var <- row.names(working.summary)
    working.summary$gender <- "Overall"
    working.summary$c_status <- "< 1 year"
    working.summary$model <- "Fully adjusted"
    working.summary$transition.name <- transition.name
    working.summary <- working.summary %>%
      mutate(hr = exp(Effect),
        hr.low = exp(`Lower 0.95`),
        hr.high = exp(`Upper 0.95`)) %>%
      select(transition.name, var, model, gender,
        c_status, hr, hr.low, hr.high)
    # output
    summary.models <- rbind(summary.models,
      working.summary)

    # cancers diagnosed 1-5y ago
    if (transition.name %in%
      c("From general population to diagnosed with COVID-19",
        "From diagnosed with COVID-19 to hospitalised with COVID-19",
        "From general population to death")) {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+rcs(age,5)+
               medea+smoke.all_time+
               a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
               a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\"1-5 years\")")),
      iter.max = 200)

    } else if (transition.name %in%
      c("From general population to hospitalised with COVID-19",
        "From diagnosed with COVID-19 to death")) {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+pol(age,2)+
               medea+smoke.all_time+
               a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
               a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\"1-5 years\")")),
      iter.max = 200)
    } else {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+rcs(age,3)+
               medea+smoke.all_time+
               a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
               a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\"1-5 years\")")),
      iter.max = 200)
    }
    working.summary <- as.data.frame(summary(m.working, antilog = FALSE))
    working.summary$var <- row.names(working.summary)
    working.summary$gender <- "Overall"
    working.summary$c_status <- "1-5 years"
    working.summary$model <- "Fully adjusted"
    working.summary$transition.name <- transition.name
    working.summary <- working.summary %>%
      mutate(hr = exp(Effect),
        hr.low = exp(`Lower 0.95`),
        hr.high = exp(`Upper 0.95`)) %>%
      select(transition.name, var, model, gender,
        c_status, hr, hr.low, hr.high)
    # output
    summary.models <- rbind(summary.models,
      working.summary)

    ## cancers diagnosed >5y ago
    if (transition.name %in%
      c("From general population to diagnosed with COVID-19",
        "From diagnosed with COVID-19 to hospitalised with COVID-19",
        "From general population to death")) {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+rcs(age,5)+
                medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\">5years\")")),
      iter.max = 200)

    } else if (transition.name %in%
      c("From general population to hospitalised with COVID-19",
        "From diagnosed with COVID-19 to death")) {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+pol(age,2)+
                medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\">5years\")")),
      iter.max = 200)
    } else {
      m.working <- cph(as.formula(paste("Surv(time, status)~ ",
        paste(cancers[i],
          "+gender+rcs(age,3)+
                 medea+smoke.all_time+
                a_autoimmune_condition + a_chronic_kidney_disease + a_copd + a_dementia +
                a_heart_disease + a_hyperlipidemia + a_hypertension + a_t2_diabetes + a_obesity"))),
      surv = TRUE, x = TRUE, y = TRUE,
      data = transition.data %>%
        filter_se(paste0("cancer==0 |
                       (", cancers[i], "==1 & c_status==\">5years\")")),
      iter.max = 200)
    }
    working.summary <- as.data.frame(summary(m.working, antilog = FALSE))
    working.summary$var <- row.names(working.summary)
    working.summary$gender <- "Overall"
    working.summary$c_status <- ">5years"
    working.summary$model <- "Fully adjusted"
    working.summary$transition.name <- transition.name
    working.summary <- working.summary %>%
      mutate(hr = exp(Effect),
        hr.low = exp(`Lower 0.95`),
        hr.high = exp(`Upper 0.95`)) %>%
      select(transition.name, var, model, gender,
        c_status, hr, hr.low, hr.high)
    # output
    summary.models <- rbind(summary.models,
      working.summary)

  }
  summary.models

}
```


```{r}
# Gathering results by transition
summary.m.healthy.diagnosis <- get.models(cancers = cancers,
  transition.data = r.healthy.diagnosis,
  transition.name = "From general population to diagnosed with COVID-19")

summary.m.healthy.hospitalised <- get.models(cancers = cancers,
  transition.data = r.healthy.hospitalised,
  transition.name = "From general population to hospitalised with COVID-19")

summary.m.healthy.death <- get.models(cancers = cancers,
  transition.data = r.healthy.death,
  transition.name = "From general population to death")

summary.m.diagnosis.hospitalised <- get.models(cancers = cancers,
  transition.data = r.diagnosis.hospitalised,
  transition.name = "From diagnosed with COVID-19 to hospitalised with COVID-19")

summary.m.diagnosis.death <- get.models(cancers = cancers,
  transition.data = r.diagnosis.death,
  transition.name = "From diagnosed with COVID-19 to death")

summary.m.hospitalised.death <- get.models(cancers = cancers,
  transition.data = r.hospitalised.death,
  transition.name = "From hospitalised with COVID-19 to death")
```


# Summary of models
```{r}
estimates <- rbind(
  summary.m.healthy.diagnosis,
  summary.m.healthy.hospitalised,
  summary.m.diagnosis.hospitalised,
  summary.m.diagnosis.death,
  summary.m.hospitalised.death,
  summary.m.healthy.death)

# save estimates
# save(estimates, file = "M:/Elena - R/Multi-state  cancer/results/2.estimates_years_hemato_solid.Rda")
# load("M:/Elena - R/Multi-state  cancer/results/2.estimates_years_hemato_solid.Rda")

# just the estimated effect of cancers
estimates <- estimates %>%
  filter(var == "cancer" | var == "solid" | var == "hematological")

summary.table <- estimates %>%
  mutate(est = paste0(nice.num2(hr), " (",
    nice.num2(hr.low), " to ",
    nice.num2(hr.high), ")"
  )) %>%
  mutate(group = paste0(model, "- ", gender, "- ", c_status)) %>%
  select(transition.name, var, group, est)

summary.table <- summary.table %>%
  pivot_wider(
    names_from = group,
    values_from = est)
# save results
# write.csv2(summary.table, "M:/Elena - R/Multi-state  cancer/results/2.HR_years_hemato_solid.csv", row.names = TRUE)
```

```{r}
# view results
kable(summary.table,
  col.names = c("Transition", "Variable",
    "Overall", "Less than 1 year",
    "1-5years", "More than 5 years"
)) %>%
  add_header_above(c("", "", "", "Years since the diagnosis of cancer" = 3)) %>%
  kable_styling(bootstrap_options = c("striped", "bordered"))  %>%
  collapse_rows(columns = 1)
```

#Plotting HR for each specific cancer type
```{r}
plot.data <- estimates %>%
  mutate(transition.name =
    ifelse(transition.name ==
      "From general population to diagnosed with COVID-19",
    "From general population\nto diagnosed\nwith COVID-19",
    ifelse(transition.name ==
      "From general population to hospitalised with COVID-19",
    "From general population\nto hospitalised\nwith COVID-19",
    ifelse(transition.name ==
      "From diagnosed with COVID-19 to hospitalised with COVID-19",
    "From diagnosed with\nCOVID-19 to hospitalised\nwith COVID-19",
    ifelse(transition.name ==
      "From diagnosed with COVID-19 to death",
    "From diagnosed with\nCOVID-19 to\ndeath",
    ifelse(transition.name ==
      "From hospitalised with COVID-19 to death",
    "From hospitalised\nwith COVID-19\nto death",
    ifelse(transition.name ==
      "From general population to death",
    "From general population\nto death",
    NA))))))) %>%
  mutate(transition.name = factor(transition.name,
    levels = c("From general population\nto diagnosed\nwith COVID-19",
      "From general population\nto hospitalised\nwith COVID-19",
      "From diagnosed with\nCOVID-19 to hospitalised\nwith COVID-19",
      "From diagnosed with\nCOVID-19 to\ndeath",
      "From hospitalised\nwith COVID-19\nto death",
      "From general population\nto death"
  )))

plot.data <- plot.data %>%
  mutate(var = str_to_title(var)) %>%
  mutate(var = factor(var,
    levels = c("Hematological",
      "Solid",
      "Cancer"))) %>%
  mutate(c_status = ifelse(c_status == "< 1 year", "<1 year",
    ifelse(c_status == ">5years", "\u22655 years",
      c_status))) %>%
  mutate(c_status = factor(c_status,
    levels = c("Overall", "\u22655 years", "1-5 years", "<1 year"))) %>%
  mutate(hr_text = paste0(nice.num2(hr), " (",
    nice.num2(hr.low), " to ",
    nice.num2(hr.high), ")"))
```


## HR for COVID-19 outcomes, by years since cancer diagnosis and cancer type (Hematological or solid cancer)

```{r, fig.width= 12}

hrs.all.hemato.solid <- plot.data %>%
  filter(transition.name != "From general population\nto death") %>%
  mutate(var = ifelse(var == "Cancer", "All cancer types",
               ifelse(var == "Hematological", "Haematological", "Solid"))) %>%
  mutate(var = factor(var, levels = c("Haematological", "Solid", "All cancer types"))) %>%
  filter(var != "All cancer types") %>%
  ggplot(aes(x = hr,
    y = var,
    xmin = hr.low,
    xmax = hr.high,
    shape = var,
    colour = var)) +
  scale_x_log10(breaks = c(0.5, 1, 4, 8),
    labels = c("0.5", "1", "4", "8"),
    limits = c(0.5, 9)) +
  facet_grid(c_status ~ transition.name, drop = TRUE,
    switch = "y") +
  geom_point(size = 2.5, position = position_dodge(width = 1)) + # , shape=20) +
  geom_errorbar(width = 0, size = 1, position = position_dodge(width = 1)) +
  scale_colour_manual(values = c("#ED0E28", "#619465", "#343633")) +
  geom_vline(
    xintercept = 1,
    colour = "grey50",
    linetype = "solid"
  ) +
  scale_y_discrete(breaks = NULL) +
  theme_bw() +
  theme(text = element_text(family = "A"),
    panel.spacing = unit(0, "lines"),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 14),
    axis.title.y = element_blank(),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title = element_text(size = 14),
    strip.text.x  = element_text(size = 12, face = "bold"),
    strip.text.y.left = element_text(size = 14, angle = 0, face = "bold"),
    strip.background = element_rect(fill = "#f7f7f7")) +
  xlab("\n aHR (with 95% CI)") +  ylab("") +
  guides(colour = guide_legend(reverse = T), shape = guide_legend(reverse = T))


hrs.all.hemato.solid


# ggsave("M:/Elena - R/Multi-state  cancer/results/gg.hrs.years.hemato.solid_cov.png", hrs.all.hemato.solid,  dpi = 300,
 #  width = 15, height = 9)
```

```{r}
# save data for plot combined with sex and age
hemato_solid <- plot.data
# save(hemato_solid, file = "M:/Elena - R/Multi-state  cancer/results/hemato_solid_toplot.Rda")
```

